[project]
name = "scene-graph"
description = "Scene Graph Project"
channels = ["nvidia/label/cuda-11.8.0", "nvidia", "conda-forge", "pytorch", "aihabitat"]
platforms = ["linux-64"]

[system-requirements]
libc = { family = "glibc", version = "2.30" }

[tasks]
post-install = { cmd = "pwd", depends_on = [] }

[dependencies]
python = ">=3.8,<3.11"
pip = ">=24.0,<25"
cuda = { version = "*", channel = "nvidia/label/cuda-11.8.0" }
pytorch-cuda = { version = "11.8.*", channel = "pytorch" }
pytorch = { version = "2.1.0", channel = "pytorch" }
torchvision = { version = "*", channel = "pytorch" }
torchaudio = { version = "*", channel = "pytorch" }
habitat-sim = { version = "==0.2.5", channel = "aihabitat" }

[pypi-dependencies]
supervision = { version = "*" }
transformers = { version = "*" }
sentencepiece = { version = "*" }
pillow = { version = "*" }
hydra-core = { version = "*"}
pandas = { version = "*" }
open3d = { version = "*" }
natsort = { version = "*" }
kornia = { version = "*" }
faiss-cpu = { version = "*" }
google-generativeai = { version = "*" }
vertexai = { version = "*" }
numpy = { version = "<2.0.0" }
segment-anything = { git = "https://github.com/facebookresearch/segment-anything.git" }
