defaults:
  - base
  - base_mapping
  - hm3d
  # - replica
  # - record3d
  - sam
  - classes
  - logging_level
  - _self_

result_root: /pub3/qasim/hm3d/data/ham-sg
image_height: 1080
image_width: 1920
max_frames: 10

detections_exp_suffix: detections # helpful label to identify your detections
force_detection: !!bool True
save_detections: !!bool True
detections_model: gemini-2.0-flash-exp

make_edges: !!bool False

# Open3D
questions: open_eqa/data/open-eqa-v0.json
questions_graph_dir: /pub3/qasim/hm3d/data/ham-sg/
questions_model: gemini-2.0-flash-exp
questions_output_dir: open_eqa/results
questions_exp_name: flat_graph
questions_dry_run : False
questions_ignore_old_results : True
max_search_depth: 20
visual_memory_size: 4

# Rooms and Floors
room_grid_resolution: 0.2
debug_folder: /home/qasim/Projects/graph-robotics/gso/debug
stride: 1
exp_suffix: r_mapping # helpful label to identify your mapping experiment


save_video: !!bool False
save_objects_all_frames: !!bool False

neighbour_radius: 0.02
downsample_voxel_size: 0.01
obj_pcd_max_points: 5000

debug_render: !!bool False
vis_render: !!bool False

denoise_interval: 5           # Run DBSCAN every k frame. This operation is heavy
filter_interval: 5            # Filter objects that have too few associations or are too small
merge_interval: 5             # Merge objects based on geometric and semantic similarity
run_denoise_final_frame: !!bool True
run_filter_final_frame: !!bool True
run_merge_final_frame: !!bool True

dbscan_remove_noise: !!bool True
dbscan_eps: 0.1
dbscan_min_points: 10

# Selection criteria of the fused object point cloud
obj_min_points: 0
obj_min_detections: 1

# For merge_overlap_objects() function
use_rerun: !!bool True
save_rerun: !!bool False

# hydra:
#   verbose: true
  # mode: MULTIRUN
  # sweeper:
  #   params:
  #     downsample_voxel_size: 0.025, 0.01, 0.001, 0.001
  #     obj_pcd_max_points: 5000, 10000, 100000, 100000