defaults:
  - base_paths

dataset_root: /Users/vaniagrawal/Desktop/VA/UCLA/Capstone/graph-robotics/graph-pad/data/frames
dataset_config: ${repo_root}/configs/dataconfigs/hm3d.yaml
scene_id: 002-hm3d-wcojb4TFT35 # 000-hm3d-BFRyYbPCCPE # 002-hm3d-wcojb4TFT35
room_types:
  - kitchen
  - living room
  - bedroom
  - dinning room
  - living and dining area
  - bathroom
  - washroom
  - hallway
  - garage
  - corridor
  - office
