dataset_name: 'scannet'
camera_params:
  image_height: 968
  image_width: 1296
  fx: 960
  fy: 960 # 1141.734073
  cx: 960 # image_height/2
  cy: 540 # image_width/2
  png_depth_scale: 1000 # The depth is in npy format, and this value should not be used
room_types:
  - apartment
  - bathroom
  - bedroom
  - library
  - bookstore
  - classroom
  - closet
  - computer cluster
  - conference room
  - copy/mail room
  - dining room
  - game room
  - gym
  - hallway
  - kitchen
  - laundry room
  - living room
  - lobby
  - office
  - stairs
  - storage
  - basement
  - garage
  - misc