name: hovsg
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - numpy
  - pytorch::faiss-gpu
  - pip
  - pip:
    - matplotlib==3.7.3
    - scipy==1.13.1
    - open3d==0.18.0
    - opencv-python
    - git+https://github.com/facebookresearch/segment-anything.git
    - torchmetrics
    - ftfy
    - tqdm
    - open-clip-torch
    - transformers
    - openai==1.3.7
    - plyfile
    - hydra-core
    - pyvista
    - scikit-fmm
    - pathos
    - opencv-python-headless==4.8.1.78
